# constantes.yaml

# Connexion à la base de données pour BV (lakartxela)
database:
  host: localhost
  name: mbourciez_pro
  user: root
  password: 
  prefix: vhs_

# Constantes de la vue
website:
  title: VHS
  title_long: VIDEO HOME SHARE
  language: FR
  logo: images/LOGO_V1.png
  logo_flag: images/flag_fr.png
  website_link: http://lakartxela.iutbayonne.univ-pau.fr/~mbourciez/VHS/ 

# Constantes de l'api
tmdb:
  api_key: "a2096553592bde8ead1b2a0f2fa59bc0"
  base_url: "https://api.themoviedb.org/3"
  image_base_url: "https://image.tmdb.org/t/p/original"


# Constantes utiles
threads:
  valeurMessageSupprime: "Ce message a été supprimé." 
  valeurUtilisateurMessageSupprime: null

# Contantes pour la sécurité
security:
  secret_key: "LMlj-S&8+j1NHAX5GHCB0$lP0oRUa99do$pCWokaF#oIoYah^8NKtCLV3U_7purUn67U30K2FD+!d2_I+KnFPKFZ4!pYgobpKE"
 

